Allow network_cli type for platforms using persistent connection
ansible-collections/community.network pull request #120
Opened 2020-09-25 05:34 UTC by ganeshrn

##### SUMMARY

Fixes:
https://github.com/ansible-collections/community.network/issues/119

*  For platforms using persistent allow network_cli connection type
   In ansible 2.6 `network_cli` connection was added as first class
   connection, however some of the community platform code was not
   updated to use `network_cli`.
*  Deprecate local connection type for platforms that use persistent
   connection framework and have cliconf and terminal plugins
   implemented.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

plugins/action/ce.py
plugins/action/cnos.py
plugins/action/enos.py
plugins/action/ironware.py
plugins/action/sros.py
plugins/module_utils/network/aireos/aireos.py
plugins/module_utils/network/aruba/aruba.py
plugins/module_utils/network/cloudengine/ce.py
plugins/module_utils/network/cnos/cnos.py
plugins/module_utils/network/enos/enos.py
plugins/module_utils/network/ironware/ironware.py

##### ADDITIONAL INFORMATION

```paste below

```

2020-09-25 05:57 UTC, felixfontein requested changes

2020-09-25 05:57 UTC, felixfontein commented on changelogs/fragments/119_fix_connection_check_issue.yml
> +- Add check for network_cli connection type in action plugins
```suggestion
- action pugins - add check for network_cli connection type (https://github.com/ansible-collections/community.network/issues/119, https://github.com/ansible-collections/community.network/pull/120).
```

2020-09-25 05:57 UTC, felixfontein commented on changelogs/fragments/119_fix_connection_check_issue.yml
> +- Deprecate connection=local support for network platforms using persistent framework
```suggestion
- Deprecate connection=local support for network platforms using persistent framework (https://github.com/ansible-collections/community.network/pull/120).
```

2020-09-25 05:57 UTC, felixfontein commented on plugins/action/ce.py
> +                     ' use connection %s' % pc.connection])
1. community.network deprecates by version, not by date (see #81).
2. This does not belong into `warnings`, but into `deprecations` (https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L2182-L2184), with the format as described here: https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/common/warnings.py#L28

2020-09-25 11:08 UTC, felixfontein commented on plugins/action/aireos.py
> +            deprecate(msg, version='4.0.0', collection_name='community.network')
I don't think this method has any effect (it stores its result in global variables which aren't read). Better use `display.deprecated()`.

2020-09-29 04:48 UTC, felixfontein approved these changes
Cannot judge all the code changes, but the things I can judge look good. If this is merged by tomorrow, it will definitely be included in community.network 1.2.0.

2020-09-29 06:03 UTC, ganeshrn commented
@felixfontein Thanks for reviewing the PR. It will be great if we can get some reviews from the individual platform owners. For platform using persistent connection framework, we would like to get away from using connection=local and promote the use of connection=network_cli.
Can we add the PR to community meeting agenda if it can help get more eyes?

2020-09-29 07:51 UTC, felixfontein commented
@ganeshrn feel free to add it to the agenda. Not sure whether it will get a lot of additional eyes, I'm not sure anyone interested in this collection attends that meeting (except @gundalow and me). It might make more sense to CC all relevant people in this PR. (Once we have ansibullbot here it should have already done it, but we don't have the bot yet...)

2020-09-29 09:41 UTC, ganeshrn commented
CC @QijunPan @TommyLike @edisonxiang @freesky-edward @hwDCN @niuzhenguo @xuxiaowei0512 @yanzhangi @zengchen1024 @zhongjun2 @istaicu @mihaibroc @ amuraleedhar @ paulquack

2020-09-29 13:03 UTC, mihaibroc commented
The changes (for Lenovo CNOS and ENOS) look good for me.
Thank you,
Mihai

2020-10-15 07:54 UTC, merged

2020-10-15 14:18 UTC, felixfontein commented
@ganeshrn thanks for implementing this!
@mihaibroc thanks for reviewing!