Cisco NSO module migration
ansible-collections/community.network pull request #142
Opened 2020-11-02 20:42 UTC by mamullen13316

##### SUMMARY
Migrate the Cisco NSO modules to the cisco.nso namespace

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
- nso_config
- nso_verify
- nso_query
- nso_action
- nso_show

##### ADDITIONAL INFORMATION
The new collection is active on Galaxy here: https://galaxy.ansible.com/cisco/nso and on Github: https://github.com/CiscoDevNet/ansible-nso. This PR is to migrate the modules in community.network  over to the new collection.  I tried to follow along with the previous Onyx PR (#74 ) which I believe was a similar migration, but please let me know if there is anything that I am missing or needs to be corrected.

2020-11-02 20:59 UTC, felixfontein requested changes
Adding negative review to avoid accidental merge.

2020-11-10 16:27 UTC, mamullen13316 commented
Hello @felixfontein,  are there any changes required for this PR to be merged and when might it be merged?   Also, will merging this PR take care of re-pointing the documentation on docs.ansible.com to the new collection or is there something separate that needs to be done to accomplish that?

2020-11-10 21:07 UTC, felixfontein commented
@mamullen13316 the PR is probably merged for 2.0.0, but with some modifications, especially w.r.t the deprecations of the redirects. We're still discussing how to do post-2.10.0 migrations in the community meeting. We've accumulated a bunch of these right now, and I think we're close to finally know how to make the move.

2020-11-27 07:41 UTC, felixfontein commented
For an example of how this PR should look like, see both f896c2986c024436a9e12ea6f9e5bbc828907dc5 (main removal) and dbae7da6bcfeea9c1c64060b577dec72b8f9f2a0 (fixes changelog fragment, removes changelog fragments).

Please note that this can only be merged once the new collection is included in Ansible 2.10.

2020-11-30 14:45 UTC, mamullen13316 commented
> For an example of how this PR should look like, see both f896c2986c024436a9e12ea6f9e5bbc828907dc5 (main removal) and dbae7da6bcfeea9c1c64060b577dec72b8f9f2a0 (fixes changelog fragment, removes changelog fragments).
> 
> Please note that this can only be merged once the new collection is included in Ansible 2.10.

Thanks I will review those commits.   What needs to be done to have the new collection included in Ansible 2.10?

2020-11-30 14:53 UTC, felixfontein commented
The conditions on the checklist https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst need to be satisfied, and it needs to be added to the Ansible build system (https://github.com/ansible-community/ansible-build-data/blob/main/2.10/ansible.in). The main ticket for discussing this should be https://github.com/CiscoDevNet/ansible-nso/issues/4

2020-11-30 22:48 UTC, mamullen13316 commented
Latest commit a2e7066 contains changes to align with f896c2986c024436a9e12ea6f9e5bbc828907dc5 and dbae7da6bcfeea9c1c64060b577dec72b8f9f2a0 as mentioned in the above comments.  I also merged the changes with a `git pull` to my local repo in order to incorporate the changes over the last 28 days, and resolved a merge conflict I had with meta/runtime.yml.  Please let me know if this looks ok.

2020-12-01 06:23 UTC, felixfontein commented
There are multiple nso-related files that are still around:
1. ./plugins/module_utils/network/nso/nso.py (and the directory containing it)
2. ./plugins/modules/network/nso/nso_action.py
3. ./plugins/doc_fragments/nso.py

Also there's no redirect for the doc_fragments plugin (for examples, see https://github.com/ansible-collections/community.general/blob/main/meta/runtime.yml#L503).

2020-12-01 14:52 UTC, mamullen13316 commented
Not sure how those files came back, they were deleted in the initial commit for this PR (7a0fc45).  It looks like maybe during the merge.  I checked just to make sure there hadn't been any changes to them since I initially opened the PR,  and there haven't been any changes for 3 months.  So scratching my head as to why they came back.  In any case,  this should take care of them as well as adding the redirect for the doc_fragment in meta/runtime.yml.

2020-12-01 18:35 UTC, felixfontein commented on meta/runtime.yml
> +    redirect: cisco.nso.nso
This is one level too far up:
```suggestion
  doc_fragments:
    nso:
      redirect: cisco.nso.nso
```

2020-12-02 22:08 UTC, felixfontein requested changes
Looks good!

Adding a negative review to prevent premature merge. Once the collection has been added to ansible.in, this can be merged. See [here](https://github.com/ansible-collections/overview/issues/128#issuecomment-730620776) and [here](https://github.com/CiscoDevNet/ansible-nso/issues/4) for more details.

2020-12-07 10:11 UTC, felixfontein approved these changes
https://github.com/ansible-community/ansible-build-data/pull/41 has been merged

2020-12-07 10:12 UTC, merged